version: "3"

services:

  frontend:
    build: .
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      admin_panel:
        aliases:
          - admin_panel

networks:
  admin_panel:
    driver: bridge