name: CI/CD

on:
  push:
    branches: [ ops/dockerization ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Copy env
      #   uses: canastro/copy-file-action@master
      #   with:
      #     source: "env/staging.env"
      #     target: ".env"
      #
      # - name: Install libraries
      #   run: npm i
      #
      # - name: Build application
      #   run: npm run build
      #
      # - name: Build image and push to docker registry
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_IMAGE }}
      #     registry: cr.yandex
      #     tags: latest
      #
      # - name: Build image and push to docker registry
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_IMAGE }}
      #     registry: cr.yandex
      #     tags: latest

      - name: Deploy app
        run: |
          echo "$HOST_IP" >> ./deploy/invetory.staging
          cat ./deploy/invetory.staging
          echo "$PRIVATE_KEY" >> ./deploy/private-key.txt
          cat ./deploy/private-key.txt
        env:
          env1: "ENV=staging"
          env2: "SSH_PRIVATE_KEY=${{ secrets.STAGING_PRIVATE_KEY }}"
          env3: "HOST_IP=${{ secrets.STAGING_IP }}"
          env4: "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}"
          env5: "BUILD_VERSION=latest"
          env6: "DOCKER_REGISTRY=cr.yandex"
          env7: "DOCKER_REGISTRY_USER=${{ secrets.DOCKER_USERNAME }}"
          env8: "DOCKER_REGISTRY_PASS=${{ secrets.DOCKER_PASSWORD }}"
          HOST_IP: "${{ secrets.STAGING_IP }}"
          PRIVATE_KEY: "${{ secrets.STAGING_PRIVATE_KEY }}"