name: CI/CD

on:
  push:
    branches: [ ops/dockerization ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Copy env
      #   uses: canastro/copy-file-action@master
      #   with:
      #     source: "env/staging.env"
      #     target: ".env"
      #
      # - name: Install libraries
      #   run: npm i
      #
      # - name: Build application
      #   run: npm run build
      #
      # - name: Build image and push to docker registry
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_IMAGE }}
      #     registry: cr.yandex
      #     tags: latest
      #
      # - name: Build image and push to docker registry
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_IMAGE }}
      #     registry: cr.yandex
      #     tags: latest

      - name: Prepare SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.STAGING_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy app
        run: |
          cd ./deploy

          echo "$PRIVATE_KEY" >> ./private-key.txt
          chmod 600 ./private-key.txt

          ./deploy.sh $ENV $HOST_IP $DOCKER_IMAGE $BUILD_VERSION $DOCKER_REGISTRY $DOCKER_REGISTRY_USER $DOCKER_REGISTRY_PASS

        env:
          ENV: "staging"
          HOST_IP: "${{ secrets.STAGING_IP }}"
          DOCKER_IMAGE: "${{ secrets.DOCKER_IMAGE }}"
          BUILD_VERSION: "latest"
          DOCKER_REGISTRY: "cr.yandex"
          DOCKER_REGISTRY_USER: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_REGISTRY_PASS: "${{ secrets.DOCKER_PASSWORD }}"
          PRIVATE_KEY: "${{ secrets.STAGING_PRIVATE_KEY }}"