name: CI

on:
  push:
    branches: [ ops/dockerization ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy env
        uses: canastro/copy-file-action@master
        with:
          source: "env/prod.env"
          target: ".env"

      - name: Install libraries
        run: npm i

      - name: Build application
        run: npm run build

      - name: Build image and push to docker registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: rc.yandex
          repository: loyal-delivery/admin_panel
          tags: latest